import type { Listing } from './types';

export const LISTINGS: Listing[] = [
  // Toyota Hilux
  { id: 'at-001', source: 'autotrader', make: 'Toyota', model: 'Hilux', variant: '2.8 GD-6 Legend 4x4 Auto', year: 2023, price: 749900, mileage: 18000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'White', province: 'Gauteng', city: 'Sandton', listedDate: '2026-04-10', description: 'Immaculate condition one-owner Hilux Legend. Full Toyota service history, still under factory warranty. Leather seats, rear diff lock, nudge bar, canopy.' },
  { id: 'at-002', source: 'autotrader', make: 'Toyota', model: 'Hilux', variant: '2.8 GD-6 Raider 4x4', year: 2022, price: 649000, mileage: 42000, condition: 'excellent', serviceHistory: true, transmission: 'manual', fuel: 'diesel', color: 'Silver', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-04-15', description: 'Cape Town dealer demo vehicle. Full service history, no accidents, fitted with sports bar and rubber liner.' },
  { id: 'cz-001', source: 'carscoza', make: 'Toyota', model: 'Hilux', variant: '2.4 GD-6 SRX 4x2', year: 2021, price: 489000, mileage: 67000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'diesel', color: 'Grey', province: 'KwaZulu-Natal', city: 'Durban', listedDate: '2026-04-20', description: 'KZN bakkie in great condition. Regular Toyota service intervals. Rubber mats, bull bar. Minor stone chips.' },
  { id: 'olx-001', source: 'olx', make: 'Toyota', model: 'Hilux', variant: '2.4 GD-6 SRX 4x2', year: 2019, price: 389000, mileage: 112000, condition: 'good', serviceHistory: false, transmission: 'manual', fuel: 'diesel', color: 'White', province: 'Gauteng', city: 'Pretoria', listedDate: '2026-05-01', description: 'Private sale. Reliable workhorse. Some scratches on the tray. Recent service done. No books but Toyota dealer can confirm history.' },
  { id: 'gum-001', source: 'gumtree', make: 'Toyota', model: 'Hilux', variant: '2.0 VVTi SRX 4x2', year: 2017, price: 265000, mileage: 178000, condition: 'fair', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'Blue', province: 'Eastern Cape', city: 'Port Elizabeth', listedDate: '2026-04-28', description: 'High mileage but runs great. New tyres. Some rust on tray. Ideal for a farm or contractor.' },
  { id: 'fb-001', source: 'facebook', make: 'Toyota', model: 'Hilux', variant: '2.7 VVTi Raider', year: 2018, price: 319000, mileage: 145000, condition: 'fair', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'Black', province: 'Limpopo', city: 'Polokwane', listedDate: '2026-05-05', description: 'Selling as is. Auto gearbox serviced 6 months ago. Canopy included. Contact for viewing.' },
  { id: 'iol-001', source: 'iol', make: 'Toyota', model: 'Hilux', variant: '2.8 GD-6 Legend RS 4x4 Auto', year: 2024, price: 869000, mileage: 5200, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Graphite', province: 'Gauteng', city: 'Johannesburg', listedDate: '2026-03-20', description: 'Brand-new 2024 model. Sat-nav, 360 camera, wireless charging, leather. Top-spec Legend RS.' },
  // VW Polo
  { id: 'at-003', source: 'autotrader', make: 'Volkswagen', model: 'Polo', variant: '1.0 TSI Comfortline', year: 2023, price: 329900, mileage: 14000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'White', province: 'Western Cape', city: 'Stellenbosch', listedDate: '2026-04-05', description: 'Low mileage Polo Comfortline. Factory warranty remaining. Apple CarPlay, cruise control.' },
  { id: 'cz-002', source: 'carscoza', make: 'Volkswagen', model: 'Polo', variant: '1.4 TDI Trendline', year: 2020, price: 219000, mileage: 78000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'diesel', color: 'Silver', province: 'Gauteng', city: 'Randburg', listedDate: '2026-04-18', description: 'Economical diesel Polo. Great fuel consumption. Full service history. Second owner.' },
  { id: 'olx-002', source: 'olx', make: 'Volkswagen', model: 'Polo', variant: '1.6 Comfortline', year: 2018, price: 159000, mileage: 98000, condition: 'good', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'Red', province: 'KwaZulu-Natal', city: 'Pietermaritzburg', listedDate: '2026-05-02', description: 'Well maintained Polo. New tyres and brake pads. Minor scratch on rear bumper. Needs nothing.' },
  { id: 'gum-002', source: 'gumtree', make: 'Volkswagen', model: 'Polo', variant: '1.4 Conceptline', year: 2015, price: 98000, mileage: 152000, condition: 'fair', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'Blue', province: 'Gauteng', city: 'Soweto', listedDate: '2026-04-30', description: 'Daily driver. Some dents and scratches. New battery. Drives well.' },
  { id: 'at-010', source: 'autotrader', make: 'Volkswagen', model: 'Polo', variant: '2.0 GTI DSG', year: 2022, price: 469000, mileage: 28000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Tornado Red', province: 'Gauteng', city: 'Sandton', listedDate: '2026-04-02', description: 'Hot hatch with DSG gearbox. Full VW service history. DCC, Canton sound system, travel assist.' },
  // Ford Ranger
  { id: 'at-004', source: 'autotrader', make: 'Ford', model: 'Ranger', variant: '3.0 V6 Wildtrak 4x4 Auto', year: 2023, price: 799000, mileage: 22000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Meteor Grey', province: 'Gauteng', city: 'Midrand', listedDate: '2026-04-12', description: 'New-gen Ranger Wildtrak. 3.0 V6 diesel. Sliding rear window, matrix LED lights, SYNC4A infotainment.' },
  { id: 'cz-003', source: 'carscoza', make: 'Ford', model: 'Ranger', variant: '2.0 SiT XLT 4x4 Auto', year: 2021, price: 579000, mileage: 55000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Arctic White', province: 'Western Cape', city: 'George', listedDate: '2026-04-22', description: 'One-owner dealer service history. Tow pack, rubber liner, sports bar.' },
  { id: 'olx-003', source: 'olx', make: 'Ford', model: 'Ranger', variant: '2.2 TDCi XLS 4x2', year: 2018, price: 329000, mileage: 128000, condition: 'good', serviceHistory: false, transmission: 'manual', fuel: 'diesel', color: 'White', province: 'Mpumalanga', city: 'Nelspruit', listedDate: '2026-05-03', description: 'Farm bakkie in great mechanical condition. Body has some bush marks. Drives perfectly.' },
  // BMW 3 Series
  { id: 'at-005', source: 'autotrader', make: 'BMW', model: '3 Series', variant: '320i M Sport Auto', year: 2022, price: 649000, mileage: 35000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Alpine White', province: 'Gauteng', city: 'Sandton', listedDate: '2026-04-08', description: 'BMW Certified Pre-Owned. M Sport package, heads-up display, harman/kardon, parking assistant.' },
  { id: 'cz-004', source: 'carscoza', make: 'BMW', model: '3 Series', variant: '318i Sport Line', year: 2021, price: 519000, mileage: 48000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Black Sapphire', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-04-19', description: 'Full BMW dealer history. Live Cockpit Pro, reversing camera, ambient lighting. No accidents.' },
  { id: 'olx-004', source: 'olx', make: 'BMW', model: '3 Series', variant: '320d M Sport', year: 2019, price: 389000, mileage: 89000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Mineral Grey', province: 'Gauteng', city: 'Centurion', listedDate: '2026-04-29', description: 'Diesel 3-series. BMW service history up to 80k. Last service done privately. Minor scuff on front bumper.' },
  { id: 'gum-003', source: 'gumtree', make: 'BMW', model: '3 Series', variant: '316i', year: 2016, price: 219000, mileage: 138000, condition: 'fair', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'White', province: 'Gauteng', city: 'Roodepoort', listedDate: '2026-05-01', description: 'High mileage BMW. Some electrical gremlins (parking sensors). Needs TLC but good mechanically.' },
  // Mercedes-Benz C-Class
  { id: 'at-006', source: 'autotrader', make: 'Mercedes-Benz', model: 'C-Class', variant: 'C 200 AMG Line Auto', year: 2022, price: 749000, mileage: 28000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Polar White', province: 'Gauteng', city: 'Bryanston', listedDate: '2026-04-06', description: 'MB Certified. AMG line with 18 AMG wheels, Burmester sound, digital cockpit. Fully optioned.' },
  { id: 'iol-002', source: 'iol', make: 'Mercedes-Benz', model: 'C-Class', variant: 'C 300 AMG Line 4MATIC', year: 2023, price: 919000, mileage: 11000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Obsidian Black', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-03-15', description: 'Virtually new C300 4MATIC. Full MB dealer service history. Night package, panoramic roof, 360 camera.' },
  { id: 'fb-002', source: 'facebook', make: 'Mercedes-Benz', model: 'C-Class', variant: 'C 180 Avantgarde', year: 2018, price: 349000, mileage: 102000, condition: 'good', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'Silver', province: 'KwaZulu-Natal', city: 'Umhlanga', listedDate: '2026-05-07', description: 'Private sale. Serviced regularly at MB. No book stamps but dealer can confirm. Needs new tyres.' },
  // Hyundai Tucson
  { id: 'at-007', source: 'autotrader', make: 'Hyundai', model: 'Tucson', variant: '1.6 T-GDI Elite DCT', year: 2023, price: 549000, mileage: 16000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Shimmering Silver', province: 'Gauteng', city: 'Fourways', listedDate: '2026-04-14', description: 'Demo model. Full panoramic roof, Bose sound, 10.25 infotainment. 5-year warranty.' },
  { id: 'cz-005', source: 'carscoza', make: 'Hyundai', model: 'Tucson', variant: '2.0 Premium', year: 2020, price: 369000, mileage: 72000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Phantom Black', province: 'Gauteng', city: 'Pretoria', listedDate: '2026-04-21', description: 'Full service history at Hyundai. Blind spot monitoring, lane departure warning, ventilated seats.' },
  { id: 'olx-005', source: 'olx', make: 'Hyundai', model: 'Tucson', variant: '2.0 GLS', year: 2018, price: 249000, mileage: 108000, condition: 'good', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'White', province: 'Eastern Cape', city: 'East London', listedDate: '2026-05-04', description: 'Good condition Tucson. New front tyres. AC works perfectly. No major mechanical issues.' },
  // Kia Sportage
  { id: 'at-008', source: 'autotrader', make: 'Kia', model: 'Sportage', variant: '1.6 T-GDI GT-Line DCT AWD', year: 2023, price: 599000, mileage: 12000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Aurora Black Pearl', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-04-09', description: 'Top-spec Sportage GT-Line AWD. Panoramic curved display, meridian sound, heated and ventilated seats.' },
  { id: 'cz-006', source: 'carscoza', make: 'Kia', model: 'Sportage', variant: '2.0 EX Auto', year: 2020, price: 359000, mileage: 68000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Sparkling Silver', province: 'Gauteng', city: 'Kempton Park', listedDate: '2026-04-23', description: 'Full Kia service history. 7-year warranty history. Minor paint scuff on driver door.' },
  // Toyota Corolla
  { id: 'at-009', source: 'autotrader', make: 'Toyota', model: 'Corolla', variant: '1.8 XS CVT', year: 2022, price: 379000, mileage: 31000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Glacier White', province: 'Gauteng', city: 'Midrand', listedDate: '2026-04-11', description: 'Toyota certified used vehicle. Full dealer history. Safety sense pre-collision system.' },
  { id: 'olx-006', source: 'olx', make: 'Toyota', model: 'Corolla', variant: '1.6 Prestige', year: 2019, price: 219000, mileage: 92000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Silver', province: 'Western Cape', city: 'Bellville', listedDate: '2026-05-01', description: 'Well looked after Corolla. Toyota stamp history. New battery. All original.' },
  { id: 'gum-004', source: 'gumtree', make: 'Toyota', model: 'Corolla', variant: '1.6 Advanced', year: 2016, price: 149000, mileage: 143000, condition: 'fair', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'Blue', province: 'KwaZulu-Natal', city: 'Durban North', listedDate: '2026-04-27', description: 'Daily driver. Some interior wear. AC serviced. Drives without issues.' },
  // Isuzu D-Max
  { id: 'at-011', source: 'autotrader', make: 'Isuzu', model: 'D-Max', variant: '3.0 TD 4x4 LS Auto', year: 2023, price: 699000, mileage: 19000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Sapphire Blue', province: 'Limpopo', city: 'Tzaneen', listedDate: '2026-04-07', description: 'Genuine Isuzu dealer demo. 5-year/90 000km warranty. Tow bar, rubber liner, snorkel.' },
  { id: 'cz-007', source: 'carscoza', make: 'Isuzu', model: 'D-Max', variant: '1.9 TD HR LS', year: 2021, price: 499000, mileage: 61000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'diesel', color: 'White', province: 'North West', city: 'Rustenburg', listedDate: '2026-04-24', description: 'One-owner Isuzu. Full dealer service history. Minor stone chips on bonnet.' },
  // Mazda CX-5
  { id: 'at-012', source: 'autotrader', make: 'Mazda', model: 'CX-5', variant: '2.5 Individual AWD Auto', year: 2022, price: 589000, mileage: 38000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Soul Red Crystal', province: 'Gauteng', city: 'Rosebank', listedDate: '2026-04-13', description: 'Mazda certified. Nappa leather, 360 view monitor, Bose sound, heated seats. Stunning Soul Red.' },
  { id: 'iol-003', source: 'iol', make: 'Mazda', model: 'CX-5', variant: '2.0 Dynamic Auto', year: 2023, price: 499000, mileage: 8000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Polymetal Grey', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-03-18', description: 'Near-new CX-5 Dynamic. Mazda Connect infotainment, lane-keep assist, traffic sign recognition.' },
  // Suzuki Swift
  { id: 'cz-008', source: 'carscoza', make: 'Suzuki', model: 'Swift', variant: '1.2 GL Auto', year: 2022, price: 219000, mileage: 28000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Phoenix Orange', province: 'Gauteng', city: 'Boksburg', listedDate: '2026-04-25', description: 'Full Suzuki dealer service history. Economical auto Swift. Great city car.' },
  { id: 'olx-007', source: 'olx', make: 'Suzuki', model: 'Swift', variant: '1.2 GL', year: 2020, price: 159000, mileage: 62000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'petrol', color: 'White', province: 'KwaZulu-Natal', city: 'Durban', listedDate: '2026-05-02', description: 'Low mileage Swift. Service history. New front tyres. Perfect commuter.' },
  { id: 'gum-005', source: 'gumtree', make: 'Suzuki', model: 'Swift', variant: '1.2 GA', year: 2017, price: 99000, mileage: 118000, condition: 'fair', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'Silver', province: 'Eastern Cape', city: 'Port Elizabeth', listedDate: '2026-05-03', description: 'High mileage but maintained. Recent clutch replacement. Starter motor new.' },
  // Hyundai i20
  { id: 'at-013', source: 'autotrader', make: 'Hyundai', model: 'i20', variant: '1.0 T-GDI Fluid DCT', year: 2023, price: 329000, mileage: 11000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Intense Blue', province: 'Gauteng', city: 'Fourways', listedDate: '2026-04-16', description: 'Near-new i20 Fluid. Wireless CarPlay, rear camera, auto emergency braking. Still in warranty.' },
  { id: 'olx-008', source: 'olx', make: 'Hyundai', model: 'i20', variant: '1.4 Fluid', year: 2020, price: 189000, mileage: 74000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'petrol', color: 'Silver', province: 'Gauteng', city: 'Alberton', listedDate: '2026-05-05', description: 'Full service history at Hyundai. Second owner. All in working order.' },
  // Renault Kwid
  { id: 'cz-009', source: 'carscoza', make: 'Renault', model: 'Kwid', variant: '1.0 Climber', year: 2022, price: 169000, mileage: 38000, condition: 'good', serviceHistory: true, transmission: 'manual', fuel: 'petrol', color: 'Orange', province: 'Gauteng', city: 'Tembisa', listedDate: '2026-04-26', description: 'Excellent entry-level SUV look. Touchscreen media, raised ground clearance.' },
  { id: 'gum-006', source: 'gumtree', make: 'Renault', model: 'Kwid', variant: '1.0 Expression', year: 2019, price: 99000, mileage: 88000, condition: 'fair', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'White', province: 'Limpopo', city: 'Mokopane', listedDate: '2026-04-29', description: 'Good budget daily. AC works. Some interior wear. Asking price negotiable.' },
  // Land Rover Defender
  { id: 'at-014', source: 'autotrader', make: 'Land Rover', model: 'Defender', variant: '110 D250 X-Dynamic SE Auto', year: 2023, price: 1349000, mileage: 14000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Fuji White', province: 'Western Cape', city: 'Stellenbosch', listedDate: '2026-04-03', description: 'Land Rover approved certified. Pivi Pro infotainment, air suspension, terrain response 2, tow pack.' },
  { id: 'iol-004', source: 'iol', make: 'Land Rover', model: 'Defender', variant: '90 P300 S Auto', year: 2022, price: 1099000, mileage: 28000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Gondwana Stone', province: 'Gauteng', city: 'Sandton', listedDate: '2026-03-22', description: 'Defender 90 petrol. Full Land Rover service history. Off-road pack, expedition roof rack.' },
  // Nissan Navara
  { id: 'cz-010', source: 'carscoza', make: 'Nissan', model: 'Navara', variant: '2.5 DDTi Pro-4X 4x4 Auto', year: 2022, price: 589000, mileage: 44000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Storm White', province: 'Gauteng', city: 'Alberton', listedDate: '2026-04-20', description: 'Navara Pro-4X adventure spec. Nissan service history. Rock sliders, snorkel, locking rear diff.' },
  { id: 'olx-009', source: 'olx', make: 'Nissan', model: 'Navara', variant: '2.3 dCi LE 4x4', year: 2019, price: 369000, mileage: 96000, condition: 'good', serviceHistory: false, transmission: 'manual', fuel: 'diesel', color: 'Grey', province: 'North West', city: 'Klerksdorp', listedDate: '2026-05-06', description: 'Good condition Navara. Recent full service. Minor body marks from farm use.' },
  // Honda Jazz
  { id: 'cz-011', source: 'carscoza', make: 'Honda', model: 'Jazz', variant: '1.5 Elegance CVT', year: 2021, price: 259000, mileage: 52000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Pearl White', province: 'Western Cape', city: 'Somerset West', listedDate: '2026-04-17', description: 'Honda dealer history. Magic seat system. Reversing camera, Honda Sensing suite.' },
  { id: 'gum-007', source: 'gumtree', make: 'Honda', model: 'Jazz', variant: '1.2 Comfort', year: 2017, price: 129000, mileage: 124000, condition: 'fair', serviceHistory: false, transmission: 'manual', fuel: 'petrol', color: 'Red', province: 'Free State', city: 'Bloemfontein', listedDate: '2026-04-28', description: 'Old reliable Jazz. Regular oil changes. Needs rear shocks. Rest good.' },
  // VW T-Roc
  { id: 'at-015', source: 'autotrader', make: 'Volkswagen', model: 'T-Roc', variant: '1.4 TSI Design DSG', year: 2022, price: 469000, mileage: 32000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Ravenna Blue', province: 'Western Cape', city: 'Cape Town', listedDate: '2026-04-04', description: 'VW approved used. Full digital cockpit, wireless CarPlay, park distance control all round.' },
  { id: 'fb-003', source: 'facebook', make: 'Volkswagen', model: 'T-Roc', variant: '2.0 TSI R-Line', year: 2021, price: 499000, mileage: 58000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Deep Black', province: 'Gauteng', city: 'Johannesburg', listedDate: '2026-05-08', description: 'Private sale. Full VW history. R-Line exterior. Minor stone chip on bonnet.' },
  // Toyota Fortuner
  { id: 'at-016', source: 'autotrader', make: 'Toyota', model: 'Fortuner', variant: '2.8 GD-6 4x4 Auto', year: 2022, price: 819000, mileage: 38000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'Attitude Black', province: 'Gauteng', city: 'Centurion', listedDate: '2026-04-01', description: 'Toyota-approved CPO. 7-seater, nudge bar, running boards. Dealer stamped book.' },
  { id: 'cz-012', source: 'carscoza', make: 'Toyota', model: 'Fortuner', variant: '2.4 GD-6 4x2 AT', year: 2020, price: 619000, mileage: 74000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'diesel', color: 'White', province: 'KwaZulu-Natal', city: 'Durban', listedDate: '2026-04-22', description: 'Full Toyota service history. 7-seater. Leather seats. Recent tyres.' },
  { id: 'olx-010', source: 'olx', make: 'Toyota', model: 'Fortuner', variant: '2.7 VVTi 4x2', year: 2017, price: 399000, mileage: 152000, condition: 'fair', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'Silver', province: 'Limpopo', city: 'Polokwane', listedDate: '2026-05-05', description: 'High mileage but solid Fortuner. Recent gearbox service. Family SUV at a budget price.' },
  // Audi A3
  { id: 'iol-005', source: 'iol', make: 'Audi', model: 'A3', variant: '35TFSI S line Stronic', year: 2023, price: 699000, mileage: 9000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Mythos Black', province: 'Gauteng', city: 'Rosebank', listedDate: '2026-03-25', description: 'Nearly new A3 Sedan S line. MMI navigation plus, virtual cockpit, matrix LED, ambient lighting.' },
  { id: 'at-017', source: 'autotrader', make: 'Audi', model: 'A3', variant: '1.4TFSI S line Auto', year: 2021, price: 529000, mileage: 44000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Glacier White', province: 'Western Cape', city: 'Paarl', listedDate: '2026-04-10', description: 'Audi approved warranty. S line styling, sports suspension, bang & olufsen sound.' },
  { id: 'fb-004', source: 'facebook', make: 'Audi', model: 'A3', variant: '1.0TFSI', year: 2018, price: 279000, mileage: 89000, condition: 'good', serviceHistory: false, transmission: 'automatic', fuel: 'petrol', color: 'Florett Silver', province: 'Gauteng', city: 'Sandton', listedDate: '2026-05-09', description: 'Well maintained A3. Recent service. Minor scuff on front bumper. Interior excellent.' },
  // Haval Jolion
  { id: 'cz-013', source: 'carscoza', make: 'Haval', model: 'Jolion', variant: '1.5T Super Luxury DCT', year: 2023, price: 399000, mileage: 22000, condition: 'excellent', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Crystal White', province: 'Gauteng', city: 'Pretoria', listedDate: '2026-04-26', description: 'Loaded Jolion. 360 camera, wireless charging, ventilated seats, 5-year warranty.' },
  { id: 'olx-011', source: 'olx', make: 'Haval', model: 'Jolion', variant: '1.5T Luxury', year: 2021, price: 289000, mileage: 68000, condition: 'good', serviceHistory: true, transmission: 'automatic', fuel: 'petrol', color: 'Black', province: 'Gauteng', city: 'Johannesburg', listedDate: '2026-05-06', description: 'Full Haval service history. Very economical crossover. No accidents.' },
];
